global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yaml

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
